drop table if exists uip_task;
drop table if exists uip_user;

create table uip_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

create table uip_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);


create table uip_serv_template (
	id bigint generated by default as identity,
	name varchar(128) not null,
	template clob not null,
	primary key (id)
);

create table uip_service(
	id bigint generated by default as identity,
	name varchar(128) not null,
	code varchar(128) not null,
	define clob not null,
	template_id bigint not null,
	primary key (id)
);

create table uip_message(
	id bigint generated by default as identity,
	create_time timestamp default current_timestamp ,
	serv_instance_id varchar(128) not null,
	message clob ,
	service_id bigint,
	order_id bigint ,
	from_ip varchar(128) ,
	aim_address varchar(128) ,
	flag  bigint,
	sender varchar(128),	
	primary key (id)
);